version: "3.8"

services:
  app:
    build: ./app
    ports:
      - "5000:5000"
    depends_on:
      - db
      - warehouse_db
    deploy:  
      resources:
        limits:
          cpus: "2"
          memory: "512M"
    environment:
      - SQLALCHEMY_DATABASE_URI=mysql://root:root@warehouse_db:3308/BrewandBrain_warehouse
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_ENV=development
    networks:
      - mynetwork

  db:
    image: mysql:8.2
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mynetwork

  warehouse_db:
    image: mysql:8.2
    ports:
      - "3309:3308"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db/warehouse_init.sql:/docker-entrypoint-initdb.d/warehouse_init.sql
    networks:
      - mynetwork

networks:
  mynetwork:
